window.SNACKS = [
  {
    "id": 1,
    "name": "Chocolate covered bacon",
    "fullNote": "Chocolate covered bacon - Polynesian",
    "park": "Resort / Hotel",
    "location": "Polynesian",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_01.png",
    "altImageFromPdf": "images/page1_1.png"
  },
  {
    "id": 2,
    "name": "Creme brulee croissant",
    "fullNote": "Creme brulee croissant",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_02.png",
    "altImageFromPdf": "images/page2_1.png"
  },
  {
    "id": 3,
    "name": "Brioche ice cream sandwich",
    "fullNote": "Brioche ice cream sandwich",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_03.png",
    "altImageFromPdf": "images/page3_1.png"
  },
  {
    "id": 4,
    "name": "Mickey beignet sundae",
    "fullNote": "Mickey beignet sundae",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_04.png",
    "altImageFromPdf": null
  },
  {
    "id": 5,
    "name": "Churro sundae",
    "fullNote": "Churro sundae",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_05.png",
    "altImageFromPdf": null
  },
  {
    "id": 6,
    "name": "Lion king ice cream sandwich",
    "fullNote": "Lion king ice cream sandwich",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_06.png",
    "altImageFromPdf": null
  },
  {
    "id": 7,
    "name": "Lunch box tart",
    "fullNote": "Lunch box tart",
    "park": "Hollywood Studios",
    "location": "Woody's Lunch Box",
    "locationInferred": true,
    "type": "snack",
    "tried": false,
    "image": "images/snack_07.png",
    "altImageFromPdf": null
  },
  {
    "id": 8,
    "name": "Grilled cheese",
    "fullNote": "Grilled cheese at Toy Story Land",
    "park": "Hollywood Studios",
    "location": "Toy Story Land",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_08.png",
    "altImageFromPdf": null
  },
  {
    "id": 9,
    "name": "Foot long mozzarella stick",
    "fullNote": "Foot long mozzarella stick",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_09.png",
    "altImageFromPdf": null
  },
  {
    "id": 10,
    "name": "Sweet and sour waffle",
    "fullNote": "Sweet and sour waffle",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_10.png",
    "altImageFromPdf": null
  },
  {
    "id": 11,
    "name": "Candied bacon",
    "fullNote": "Candied bacon",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_11.png",
    "altImageFromPdf": null
  },
  {
    "id": 12,
    "name": "Peanut butter and jelly croissant",
    "fullNote": "Peanut butter and jelly croissant - All Star Sports",
    "park": "Resort / Hotel",
    "location": "All Star",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_12.png",
    "altImageFromPdf": null
  },
  {
    "id": 13,
    "name": "Pizza/cinnamon pretzel",
    "fullNote": "Pizza/cinnamon pretzel - Coronado",
    "park": "Resort / Hotel",
    "location": "Coronado",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_13.png",
    "altImageFromPdf": null
  },
  {
    "id": 14,
    "name": "Baked macaroni and pulled pork",
    "fullNote": "Baked macaroni and pulled pork - Animal BBQ",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_14.png",
    "altImageFromPdf": null
  },
  {
    "id": 15,
    "name": "Chicken and waffle",
    "fullNote": "Chicken and waffle - Sleepy Hollow",
    "park": "Magic Kingdom",
    "location": "Sleepy Hollow",
    "locationInferred": true,
    "type": "snack",
    "tried": false,
    "image": "images/snack_15.png",
    "altImageFromPdf": null
  },
  {
    "id": 16,
    "name": "Chocolate chip cookie dough croissant",
    "fullNote": "Chocolate chip cookie dough croissant - Amorette's Disney Springs",
    "park": "Disney Springs",
    "location": "Disney Springs",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_16.png",
    "altImageFromPdf": null
  },
  {
    "id": 17,
    "name": "Strawberry cereal Mickey treat",
    "fullNote": "Strawberry cereal Mickey treat - Animal Kingdom Zuri",
    "park": "Animal Kingdom",
    "location": "Animal Kingdom",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_17.png",
    "altImageFromPdf": null
  },
  {
    "id": 18,
    "name": "Deep fried Hawaiian roll",
    "fullNote": "Deep fried Hawaiian roll - The BoardWalk",
    "park": "BoardWalk",
    "location": "Boardwalk",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_18.png",
    "altImageFromPdf": null
  },
  {
    "id": 19,
    "name": "Caramel apple donuts",
    "fullNote": "Caramel apple donuts - Magic Friar's Nook",
    "park": "Magic Kingdom",
    "location": "Friar's Nook",
    "locationInferred": true,
    "type": "snack",
    "tried": false,
    "image": "images/snack_19.png",
    "altImageFromPdf": null
  },
  {
    "id": 20,
    "name": "Cookie dough ice cream sandwich",
    "fullNote": "Cookie dough ice cream sandwich - Terra Treats Animal Kingdom",
    "park": "Animal Kingdom",
    "location": "Animal Kingdom",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_20.png",
    "altImageFromPdf": null
  },
  {
    "id": 21,
    "name": "Lemon bolle",
    "fullNote": "Lemon bolle - Epcot",
    "park": "EPCOT",
    "location": "EPCOT",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_21.png",
    "altImageFromPdf": null
  },
  {
    "id": 22,
    "name": "Lemon violet macaron",
    "fullNote": "Lemon violet macaron",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_22.png",
    "altImageFromPdf": null
  },
  {
    "id": 23,
    "name": "Cheddar bacon tots",
    "fullNote": "Cheddar bacon tots - Friar's Nook",
    "park": "Magic Kingdom",
    "location": "Friar's Nook",
    "locationInferred": true,
    "type": "snack",
    "tried": false,
    "image": "images/snack_23.png",
    "altImageFromPdf": null
  },
  {
    "id": 24,
    "name": "Ham and cheese",
    "fullNote": "Ham and cheese at Gaston's",
    "park": "Magic Kingdom",
    "location": "Gaston's Tavern",
    "locationInferred": true,
    "type": "snack",
    "tried": false,
    "image": "images/snack_24.png",
    "altImageFromPdf": null
  },
  {
    "id": 25,
    "name": "Fairfax Fare Mickey waffles and bacon",
    "fullNote": "Fairfax Fare Mickey waffles and bacon - Hollywood",
    "park": "Hollywood Studios",
    "location": "Hollywood",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_25.png",
    "altImageFromPdf": null
  },
  {
    "id": 26,
    "name": "Ronto wraps",
    "fullNote": "Ronto wraps - Hollywood",
    "park": "Hollywood Studios",
    "location": "Hollywood",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_26.png",
    "altImageFromPdf": null
  },
  {
    "id": 27,
    "name": "Chicken stuffed Mickey waffles",
    "fullNote": "Chicken stuffed Mickey waffles - Coronado",
    "park": "Resort / Hotel",
    "location": "Coronado",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_27.png",
    "altImageFromPdf": null
  },
  {
    "id": 28,
    "name": "Smores bar",
    "fullNote": "Smores bar - Regal Eagle Smokehouse - Epcot",
    "park": "EPCOT",
    "location": "EPCOT",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_28.png",
    "altImageFromPdf": null
  },
  {
    "id": 29,
    "name": "Mickey strawberry cookie sandwich",
    "fullNote": "Mickey strawberry cookie sandwich - candy shops throughout park",
    "park": "Unclear / Review",
    "location": "",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_29.png",
    "altImageFromPdf": null
  },
  {
    "id": 30,
    "name": "Donut hole skewers at Everglazed",
    "fullNote": "Donut hole skewers at Everglazed - Disney Springs",
    "park": "Disney Springs",
    "location": "Disney Springs",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_30.png",
    "altImageFromPdf": null
  },
  {
    "id": 31,
    "name": "Frozen vanilla wafer sandwich",
    "fullNote": "Frozen vanilla wafer sandwich - Japan Pavilion",
    "park": "EPCOT",
    "location": "Japan Pavilion",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_31.png",
    "altImageFromPdf": null
  },
  {
    "id": 32,
    "name": "Fairy bread cake",
    "fullNote": "Fairy bread cake - Animal Kingdom",
    "park": "Animal Kingdom",
    "location": "Animal Kingdom",
    "locationInferred": false,
    "type": "snack",
    "tried": false,
    "image": "images/snack_32.png",
    "altImageFromPdf": null
  }
];
