window.SNACKS = [

{ id: 1, name: "Chocolate Covered Bacon", park: "Resort", location: "Kona Island", image: "snack_01.png", tried: false },
{ id: 2, name: "Creme Brulee Croissant", park: "Magic Kingdom", location: "Gastons Tavern", image: "snack_02.png", tried: false },
{ id: 3, name: "Brioche Ice Cream Sandwich", park: "EPCOT", location: "Artisan des Glaces", image: "snack_03.png", tried: false },
{ id: 4, name: "Mickey Beignet Sundae", park: "Resort", location: "Scat Cats Cafe", image: "snack_04.png", tried: false },
{ id: 5, name: "Churro Sundae", park: "EPCOT", location: "La Cantina de San Angel", image: "snack_05.png", tried: false },
{ id: 6, name: "Cookie Dough Ice Cream Sandwich", park: "Animal Kingdom", location: "Terra Treats", image: "snack_06.png", tried: false },
{ id: 7, name: "Lunch Box Tart", park: "Hollywood Studios", location: "Woodys Lunch Box", image: "snack_07.png", tried: false },
{ id: 8, name: "Grilled Cheese", park: "Hollywood Studios", location: "Woodys Lunch Box", image: "snack_08.png", tried: false },
{ id: 9, name: "Mozzarella Stick", park: "Magic Kingdom", location: "Tonys Town Square", image: "snack_09.png", tried: false },
{ id: 10, name: "Sweet Spicy Waffle", park: "Magic Kingdom", location: "Sleepy Hollow", image: "snack_10.png", tried: false },
{ id: 11, name: "Candied Bacon", park: "Magic Kingdom", location: "Golden Oak Outpost", image: "snack_11.png", tried: false },
{ id: 12, name: "PBJ Croissant", park: "Resort", location: "Pop Century", image: "snack_12.png", tried: false },
{ id: 13, name: "Pretzel", park: "Disney Springs", location: "Wetzels Pretzels", image: "snack_13.png", tried: false },
{ id: 14, name: "Mac and Pork", park: "Animal Kingdom", location: "Flame Tree BBQ", image: "snack_14.png", tried: false },
{ id: 15, name: "Chicken and Waffles", park: "Resort", location: "Topolinos Terrace", image: "snack_15.png", tried: false },
{ id: 16, name: "Cookie Dough Croissant", park: "Resort", location: "Contempo Cafe", image: "snack_16.png", tried: false },
{ id: 17, name: "Strawberry Mickey Treat", park: "Animal Kingdom", location: "Zuris Sweets Shop", image: "snack_17.png", tried: false },
{ id: 18, name: "Hawaiian Roll", park: "BoardWalk", location: "Blue Ribbon Corn Dogs", image: "snack_18.png", tried: false },
{ id: 19, name: "Caramel Apple Donuts", park: "Magic Kingdom", location: "Friars Nook", image: "snack_19.png", tried: false },
{ id: 20, name: "Lemon Bolle", park: "EPCOT", location: "Norway Beer Cart", image: "snack_20.png", tried: false },
{ id: 21, name: "Lemon Macaron", park: "EPCOT", location: "Sunshine Seasons", image: "snack_21.png", tried: false },
{ id: 22, name: "Cheddar Bacon Tots", park: "Magic Kingdom", location: "Friars Nook", image: "snack_22.png", tried: false },
{ id: 23, name: "Ham Sandwich", park: "Magic Kingdom", location: "Gastons Tavern", image: "snack_23.png", tried: false },
{ id: 24, name: "Mickey Waffles Bacon", park: "Hollywood Studios", location: "Fairfax Fare", image: "snack_24.png", tried: false },
{ id: 25, name: "Ronto Wrap", park: "Hollywood Studios", location: "Ronto Roasters", image: "snack_25.png", tried: false },
{ id: 26, name: "Stuffed Mickey Waffles", park: "Resort", location: "Grand Floridian Cafe", image: "snack_26.png", tried: false },
{ id: 27, name: "Smores Bar", park: "EPCOT", location: "Regal Eagle", image: "snack_27.png", tried: false },
{ id: 28, name: "Strawberry Cookie Sandwich", park: "Magic Kingdom", location: "Big Top Souvenirs", image: "snack_28.png", tried: false },
{ id: 29, name: "Donut Skewers", park: "Disney Springs", location: "Everglazed", image: "snack_29.png", tried: false },
{ id: 30, name: "Vanilla Wafer Sandwich", park: "EPCOT", location: "Mitsukoshi", image: "snack_30.png", tried: false },
{ id: 31, name: "Fairy Bread Cake", park: "Animal Kingdom", location: "Pizzafari", image: "snack_31.png", tried: false },
{ id: 32, name: "Pretzel Bites", park: "Animal Kingdom", location: "Isle of Java", image: "snack_32.png", tried: false },
{ id: 33, name: "Chicken Goof Ups", park: "EPCOT", location: "Grab N Goof", image: "snack_33.png", tried: false }

];
