
window.SNACKS = [
  { id: 1, name: "Chocolate Covered Bacon", park: "Resort / Polynesian", location: "Kona Island", image: "snack_01.png" },
  { id: 2, name: "Crème Brulee Croissant", park: "Magic Kingdom", location: "Gaston’s Tavern", image: "snack_02.png" },
  { id: 3, name: "Brioche Ice Cream Sandwich", park: "EPCOT", location: "L’Artisan des Glaces (France)", image: "snack_03.png" },
  { id: 4, name: "Mickey Beignet Sundae", park: "Resort / Port Orleans", location: "Scat Cat’s Café", image: "snack_04.png" },
  { id: 5, name: "Churro Sundae", park: "EPCOT", location: "La Cantina de San Angel (Mexico)", image: "snack_05.png" },
  { id: 6, name: "Cookie Dough Ice Cream Sandwich", park: "Animal Kingdom", location: "Terra Treats", image: "snack_06.png" },
  { id: 7, name: "Lunch Box Tart", park: "Hollywood Studios", location: "Woody’s Lunch Box", image: "snack_07.png" },
  { id: 8, name: "Grilled Cheese", park: "Hollywood Studios", location: "Woody’s Lunch Box", image: "snack_08.png" },
  { id: 9, name: "Foot Long Mozzarella Stick", park: "Magic Kingdom", location: "Tony’s Town Square / Blue Ribbon Corn Dogs (BoardWalk)", image: "snack_09.png" },
  { id: 10, name: "Sweet and Spicy Waffle", park: "Magic Kingdom", location: "Sleepy Hollow", image: "snack_10.png" },
  { id: 11, name: "Candied Bacon", park: "Magic Kingdom", location: "Golden Oak Outpost", image: "snack_11.png" },
  { id: 12, name: "Peanut Butter and Jelly Croissant", park: "Resort / Pop Century", location: "", image: "snack_12.png" },
  { id: 13, name: "Pizza / Cinnamon Pretzel", park: "Disney Springs", location: "Wetzel’s Pretzels", image: "snack_13.png" },
  { id: 14, name: "Baked Macaroni and Pulled Pork", park: "Animal Kingdom", location: "Flame Tree Barbecue", image: "snack_14.png" },
  { id: 15, name: "Chicken and Waffles", park: "Resort / Riviera", location: "Topolino’s Terrace", image: "snack_15.png" },
  { id: 16, name: "Chocolate Chip Cookie Dough Croissant", park: "Resort / Contemporary", location: "Contempo Café", image: "snack_16.png" },
  { id: 17, name: "Strawberry Cereal Mickey Treat", park: "Animal Kingdom", location: "Zuri’s Sweets Shop", image: "snack_17.png" },
  { id: 18, name: "Deep Fried Hawaiian Roll", park: "BoardWalk", location: "Blue Ribbon Corn Dogs", image: "snack_18.png" },
  { id: 19, name: "Caramel Apple Donuts", park: "Magic Kingdom", location: "Friar’s Nook", image: "snack_19.png" },
  { id: 20, name: "Lemon Bolle", park: "EPCOT", location: "Norway Beer Cart (seasonal)", image: "snack_20.png" },
  { id: 21, name: "Lemon Violet Macaron", park: "EPCOT", location: "Sunshine Seasons (seasonal)", image: "snack_21.png" },
  { id: 22, name: "Cheddar Bacon Tots", park: "Magic Kingdom", location: "Friar’s Nook", image: "snack_22.png" },
  { id: 23, name: "Ham and Gruyere Sandwich", park: "Magic Kingdom", location: "Gaston’s Tavern", image: "snack_23.png" },
  { id: 24, name: "Mickey Waffles and Bacon", park: "Hollywood Studios", location: "Fairfax Fare", image: "snack_24.png" },
  { id: 25, name: "Ronto Wraps", park: "Hollywood Studios", location: "Ronto Roasters", image: "snack_25.png" },
  { id: 26, name: "Chicken Stuffed Mickey Waffles", park: "Resort / Grand Floridian", location: "Grand Floridian Café", image: "snack_26.png" },
  { id: 27, name: "Smores Bar", park: "EPCOT", location: "Regal Eagle Smokehouse (seasonal)", image: "snack_27.png" },
  { id: 28, name: "Mickey Strawberry Cookie Sandwich", park: "Magic Kingdom", location: "Big Top Souvenirs / Goofy’s Candy Company", image: "snack_28.png" },
  { id: 29, name: "Donut Hole Skewers", park: "Disney Springs", location: "Everglazed Donuts", image: "snack_29.png" },
  { id: 30, name: "Frozen Vanilla Wafer Sandwich", park: "EPCOT", location: "Mitsukoshi (Japan Pavilion)", image: "snack_30.png" },
  { id: 31, name: "Fairy Bread Cake", park: "Animal Kingdom", location: "Pizzafari", image: "snack_31.png" }
];
